name: mixture
path_type: mixture
use_graph_kernel_for_harm_pitch: false

schedule:
  span_shift: 0.20
  e_ss_shift: 0.32
  e_ns_shift: 0.48
  note_shift: 0.64
  temperature: 0.12

prior:
  active_on_prob: 0.15
  e_ns_non_none_prob: 0.04
  e_ss_non_none_prob: 0.03

train_time:
  t_min: 0.01
  t_max: 0.99

sampling:
  num_steps: 64
  t_start: 0.001
  t_end: 0.999
